# Pensa Terraform Tests for PRs

name: Devops Challange Plan
env: 
  CONFIG_DIRECTORY: "./"

on:
  push:
    branches:
      - '**'
    paths:
      - '**'    
  workflow_dispatch:

jobs:
  test_env_codebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Clone DevOps Repo
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0
          
      - name: Set Branch
        run: echo "BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
        
      - name: Terraform Init
        id: init
        run: terraform init
        
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

